resources:
  containers:
  - container: nv-bionic-wasm
    image: nventive/wasm-build:1.2

jobs:
- template: .vsts-win-build.yml
  parameters:
    name: Windows
    pool:
      vmImage: 'vs2017-win2016'

- template: .vsts-linux-build.yml
